# Generated by Django 2.2.5 on 2019-12-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calcificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Homogeneidad', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('Contraste', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('Disimilitud', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('Entropia', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('Energia', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('Agrupacion', models.IntegerField(null=True)),
                ('Lateralidad', models.IntegerField(null=True)),
                ('Profundidad', models.IntegerField(null=True)),
                ('DistanciaPezon', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('DistanciaToracica', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('DistanciaExternon', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('Forma', models.IntegerField(null=True)),
                ('Bordes', models.IntegerField(null=True)),
                ('Area', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('Maligna', models.IntegerField(null=True)),
            ],
        ),
    ]
