# Generated by Django 2.2.5 on 2019-12-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcificacion',
            name='Area',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='calcificacion',
            name='Contraste',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='calcificacion',
            name='Disimilitud',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='calcificacion',
            name='DistanciaExternon',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='calcificacion',
            name='DistanciaPezon',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='calcificacion',
            name='DistanciaToracica',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='calcificacion',
            name='Energia',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='calcificacion',
            name='Entropia',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='calcificacion',
            name='Homogeneidad',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
