# Generated by Django 2.1.3 on 2020-01-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calcificacion', '0002_auto_20191215_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcificacion',
            name='Media',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='calcificacion',
            name='birads',
            field=models.CharField(help_text='BI-RADS', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='calcificacion',
            name='nombreCalcif',
            field=models.CharField(help_text='Nombre de la Calcificación', max_length=30, null=True),
        ),
    ]
